Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/betelgeuse/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/betelgeuse/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esptool/__init__.py", line 1314, in _main
    main()
  File "/home/betelgeuse/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esptool/__init__.py", line 1036, in main
    operation_func(esp, args)
  File "/home/betelgeuse/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esptool/cmds.py", line 491, in write_flash
    if set_flash_size and set_flash_size > flash_end:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'NoneType'
CMake Error at run_serial_tool.cmake:66 (message):
  
  /home/betelgeuse/.espressif/python_env/idf5.3_py3.11_env/bin/python;;/home/betelgeuse/appdata/esp/esp-adf/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



make[3]: *** [CMakeFiles/flash.dir/build.make:70: CMakeFiles/flash] Error 1
make[2]: *** [CMakeFiles/Makefile2:3016: CMakeFiles/flash.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3023: CMakeFiles/flash.dir/rule] Error 2
make: *** [Makefile:312: flash] Error 2
